update-cron-runme

diff --git a/bin/runme b/bin/runme
--- a/bin/runme
+++ b/bin/runme
@@ -5,20 +5,17 @@ LOG="$ROOT/log/runme.log"
 NEWAPP=""
 PID=""
 
-sites="
-www.2bees.com
-"
+site="www.2bees.com"
 
 echo "Starting check..." > $LOG
 
-for site in $sites; do
-  app="$ROOT/$site"
-  cd $app
+app="$ROOT/$site"
+[ ! -d "$app" ] && echo "$app not found!" && exit 1
+cd $app
   PID=$(ps -ef |grep $app | grep forever | awk '{ print $2 }')
   ( (echo "checking if $app is active") && [[ "$PID" == "" ]] && ./runme ) >> $LOG 2>&1
 
-  NEWAPP=`git pull | grep "up-to-date"`
-  ( (echo "checking git changes...") && \
-    [ -d "$app" ] && \
-    ( [[ -z "$NEWAPP" ]] && ./runme || echo "no change." ) >> $LOG  2>&1 &
-done
+NEWAPP=$(git pull | grep "up-to-date")
+  (echo "checking git changes...") && \
+    ( [[ -z "$NEWAPP" ]] && ./runme || echo "no change." ) >> $LOG  2>&1
+
